version: '3.8'

services:
  client:
    build: .
    container_name: client
    environment:
      - SPRING_PROFILE=prod
    ports:
      - "8090:8090"
    depends_on:
      keycloak:
        condition: service_healthy
    restart: always
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.3
    container_name: my-keycloak
    restart: always
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mysql
      - KC_DB_URL_HOST=db
      - KC_DB_SCHEMA=keycloak
      - KC_DB_URL=jdbc:mysql://db:3306/keycloak
      - KC_DB_URL_PORT=3306
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=root
    volumes:
      - ./custom-theme:/opt/keycloak/themes/custom-theme
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    command:
      - start-dev
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      timeout: 10s
      retries: 5
  db:
    image: mysql:8
    container_name: keycloak_mysql
    restart: always
    tty: true
    ports:
      - "33306:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=keycloak
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10